In [12]:
import numpy as np
ar=np.array([[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8]])
ar
print(ar,type(ar))
print(ar.ndim)#判断是几维数组
print(ar.shape)
print(ar.size)#元素个数
print(type(ar),ar.dtype)
print(ar.itemsize)#每个元素字节大小
print(ar.data)

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]] <class 'numpy.ndarray'>
2
(3, 6)
18
<class 'numpy.ndarray'> int32
4


In [19]:
ar1=np.array(range(10))
ar2=np.array(10)
ar3=np.array([1,2,3,4,5,6])
ar4=np.array([[1,2,3],['a','b','c','d']])#个数不一样时变为一维数组
ar5=np.array([[1,2,3],['a','b','c']])
print(ar1)
print(ar2)
print(ar3)
print(ar4,ar4.ndim)
print(ar5,ar5.ndim)

[0 1 2 3 4 5 6 7 8 9]
10
[1 2 3 4 5 6]
[list([1, 2, 3]) list(['a', 'b', 'c', 'd'])] 1
[['1' '2' '3']
 ['a' 'b' 'c']] 2


In [20]:
print(np.random.rand(10).reshape(2,5))

[[0.19242378 0.24268677 0.1908527  0.11091509 0.16684765]
 [0.74768741 0.76570983 0.15930961 0.15178898 0.57322732]]


In [22]:
print(np.arange(10))
print(np.arange(5,10))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [26]:
print(np.linspace(10,20,num=20))#等差
print(np.linspace(10,20,num=21,endpoint=False))
#endpoint表示最后一个数包含或不包含
print(np.linspace(10,20,num=21,retstep=True))#restep是显示步长

[10.         10.52631579 11.05263158 11.57894737 12.10526316 12.63157895
 13.15789474 13.68421053 14.21052632 14.73684211 15.26315789 15.78947368
 16.31578947 16.84210526 17.36842105 17.89473684 18.42105263 18.94736842
 19.47368421 20.        ]
[10.         10.47619048 10.95238095 11.42857143 11.9047619  12.38095238
 12.85714286 13.33333333 13.80952381 14.28571429 14.76190476 15.23809524
 15.71428571 16.19047619 16.66666667 17.14285714 17.61904762 18.0952381
 18.57142857 19.04761905 19.52380952]
(array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ]), 0.5)


In [32]:
print(np.zeros(10))
print(np.zeros((2,5),dtype=np.int))
ar=np.array([list(range(10)),list(range(10,20))])
print(ar)
print(np.zeros_like(ar))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [34]:
ar5=np.ones(9)
print(ar5)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [35]:
print(np.eye(5))#创建一个正方形的N*N的单位矩阵，对角线值为1，其余为0

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
a1=np.array([1,2,'a','hello',[1,2,3],{'two':200,'one':100}])
print(a1,a1.shape)

[1 2 'a' 'hello' list([1, 2, 3]) {'two': 200, 'one': 100}] (6,)


In [41]:
print(np.arange(5,15))

[ 5  6  7  8  9 10 11 12 13 14]


In [42]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [45]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


通用函数

In [46]:
ar1=np.arange(10)
ar2=np.zeros((2,5))
print(ar1)
print(ar2)
print(ar1.T)
print(ar2.T)#行列转置

[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [48]:
print(ar1.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [50]:
print(np.ones((10,10)).reshape(5,20))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [51]:
print(np.reshape(np.arange(16),(2,8)))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [53]:
print(np.resize(np.arange(5),(3,4)))#多删少补
print(np.resize(np.arange(14),(3,4)))

[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [54]:
#数组复制
ar1=np.arange(10)
ar2=ar1
print(ar1 is ar2)

True


In [55]:
ar1[2]=100
ar2

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [56]:
ar3=ar1.copy()
ar1[3]=1000
ar3

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [57]:
ar1

array([   0,    1,  100, 1000,    4,    5,    6,    7,    8,    9])

In [62]:
print(np.arange(10).resize(2,6))
s=np.arange(10)
print(np.resize(s,(2,6)))#生成新的数组
print(s.resize(2,6))#改变s本身
print(s)

None
[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]
None
[[0 1 2 3 4 5]
 [6 7 8 9 0 0]]


In [64]:
#改变数组类型
ar1=np.arange(10,dtype=float)
ar1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [66]:
ar2=ar1.astype(np.int64)
print(ar1,ar1.dtype)
print(ar2,ar2.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int64


In [84]:
#数组堆叠
a=np.arange(5)
b=np.arange(5,9)
print(a)
print(b)
print(np.hstack((a,b)))

a=np.array([[1],[2],[3]])
b=np.array([['a'],['b'],['c']])
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

a=np.arange(5)
b=np.arange(5,10)
print(np.stack((a,b),axis=1))
print(np.stack((a,b),axis=0))
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[0 1 2 3 4]
[5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[[1]
 [2]
 [3]]
[['a']
 ['b']
 ['c']]
[['1']
 ['2']
 ['3']
 ['a']
 ['b']
 ['c']]
[['1' 'a']
 ['2' 'b']
 ['3' 'c']]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [88]:
#数组拆分
ar=np.arange(16).reshape(4,4)
print(ar)
print(np.hsplit(ar,2)[0])
print(np.vsplit(ar,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [94]:
#数组运算
ar=np.arange(6).reshape(2,3)
print(ar+10)
print(ar*2)
print(ar)
print(ar.max())
print(ar.min())
print(ar.mean())
print(ar.std())
print(ar.var())#方差
print(ar.sum(),np.sum(ar,axis=0))#axis=0，按行求和，axis=1按列求和

[[10 11 12]
 [13 14 15]]
[[ 0  2  4]
 [ 6  8 10]]
[[0 1 2]
 [3 4 5]]
5
0
2.5
1.707825127659933
2.9166666666666665
15 [3 5 7]


In [95]:
#作业
print(np.arange(20).reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [107]:
a=np.arange(20)
print(np.resize(a,(5,6)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]]


In [115]:
a=np.arange(16).reshape(4,4)
# print(a)
b=a.astype(np.str)
print(b)

[['0' '1' '2' '3']
 ['4' '5' '6' '7']
 ['8' '9' '10' '11']
 ['12' '13' '14' '15']]


In [120]:
a=np.arange(16).reshape(4,4)
print(a)
b=a*10+100
print(b)
print(b.mean())
print(b.sum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[100 110 120 130]
 [140 150 160 170]
 [180 190 200 210]
 [220 230 240 250]]
175.0
2800
